import type { PortfolioData } from "@/lib/types";

export const fallbackData: PortfolioData = {
  profile: {
    full_name: "Sarthak Bhandari",
    tagline: "Software · Hardware · Interfaces",
    bio: "Tech enthusiast and vibe coder exploring the space between ideas and execution.",
    avatar_url: "/media/profile/avatar.png",
    email: "sarthakbhandari172@gmail.com",
    location: "Nepal",
    hero_label: "System Online — Digital Portfolio",
    hero_display_title: "Sarthak Bhandari",
    hero_accent_title: "Digital Portfolio",
    hero_roles: ["Web Builder", "Automation Explorer", "Visual Design Learner"],
    hero_primary_cta_text: "View Work",
    hero_primary_cta_url: "#work",
    hero_secondary_cta_text: "Enter Portal",
    hero_secondary_cta_url: "#services",
    status_text: "Available for selected projects",
  },
  skills: [
    { id: 1, name: "PHP & PDO", category: "Languages", proficiency: 85, icon: "PHP", sort_order: 1 },
    { id: 2, name: "MySQL / PostgreSQL", category: "Data", proficiency: 80, icon: "DB", sort_order: 2 },
    { id: 3, name: "JavaScript / TypeScript", category: "Languages", proficiency: 85, icon: "JS", sort_order: 3 },
    { id: 4, name: "CSS & Interface Design", category: "Frontend", proficiency: 90, icon: "UI", sort_order: 4 },
    { id: 5, name: "Next.js", category: "Frameworks", proficiency: 70, icon: "NX", sort_order: 5 },
    { id: 6, name: "Supabase", category: "Cloud", proficiency: 70, icon: "SB", sort_order: 6 },
    { id: 7, name: "Git & GitHub", category: "Tools", proficiency: 80, icon: "GT", sort_order: 7 },
    { id: 8, name: "Hardware Prototyping", category: "Hardware", proficiency: 60, icon: "HW", sort_order: 8 },
  ],
  projects: [
    {
      id: 1,
      title: "Portfolio Engine",
      slug: "portfolio-engine",
      category: "Web Platform",
      description: "A dynamic portfolio with an authenticated content dashboard, structured data and responsive interface.",
      tech_stack: ["Next.js", "Supabase", "TypeScript"],
      thumbnail_url: "/media/projects/project-1.jpg",
      external_url: null,
      live_url: "#",
      github_url: "https://github.com/sarthakbhandari172-blip",
      icon_text: "WEB",
      featured: true,
      sort_order: 1,
      is_active: true,
      thumbnail_fit: "cover",
      thumbnail_position: "center center",
    },
    {
      id: 2,
      title: "Interface Experiments",
      slug: "interface-experiments",
      category: "UI Systems",
      description: "Interface studies focused on motion, hierarchy and clear technical presentation.",
      tech_stack: ["CSS", "JavaScript", "Figma"],
      thumbnail_url: "/media/projects/project-2.jpg",
      external_url: null,
      live_url: "#",
      github_url: "https://github.com/sarthakbhandari172-blip",
      icon_text: "UI",
      featured: true,
      sort_order: 2,
      is_active: true,
      thumbnail_fit: "cover",
      thumbnail_position: "center center",
    },
  ],
  experience: [
    {
      id: 1,
      company: "Independent Projects",
      role: "Software and Interface Development",
      period: "2025 — Present",
      description: "Building web interfaces, automation experiments and database-backed applications.",
      icon: "01",
      status: "Current",
      sort_order: 1,
    },
    {
      id: 2,
      company: "Hardware Exploration",
      role: "Prototyping and Systems Learning",
      period: "2024 — Present",
      description: "Exploring electronics, physical computing and the connection between hardware and software.",
      icon: "02",
      status: "Ongoing",
      sort_order: 2,
    },
  ],
  services: [
    ["Business Websites", "Responsive websites structured around clear content, performance and usability.", "WEB"],
    ["Portfolio Websites", "Focused portfolio systems for presenting work, experience and technical identity.", "PF"],
    ["Landing Pages", "Single-purpose pages designed around one message and one clear action.", "LP"],
    ["Website Redesign", "Interface and structure improvements for existing websites.", "UI"],
    ["Workflow Automation", "Practical automation connecting forms, data and external services.", "AU"],
    ["AI-Assisted Builds", "Human-directed development accelerated by modern AI tools.", "AI"],
    ["Visual Assets", "Project thumbnails and supporting graphics for digital products.", "VA"],
    ["Web Setup", "Essential deployment, domain and platform setup for a new web presence.", "WS"],
  ].map(([title, description, icon_text], index) => ({
    id: index + 1,
    title,
    description,
    icon_text,
    badge_text: "Service",
    badge_style: index % 2 ? "cyan" : "ok",
    cta_text: "Discuss project",
    cta_url: "#contact",
    sort_order: index + 1,
    is_active: true,
  })),
  sections: {
    about: {
      section_key: "about",
      label: "Identity File",
      title: "About",
      accent: "Sarthak",
      description: "A multidisciplinary builder exploring visual design, software, automation and the interfaces connecting them.",
    },
    skills: {
      section_key: "skills",
      label: "System Modules",
      title: "Skills",
      accent: "Inventory",
      description: "Tools and technologies currently used across design, development and experimentation.",
    },
    work: {
      section_key: "work",
      label: "Selected Work",
      title: "Featured",
      accent: "Projects",
      description: "Projects that connect ideas, implementation and clear interface design.",
    },
    services: {
      section_key: "services",
      label: "Capabilities",
      title: "What I",
      accent: "Build",
      description: "Focused digital work across software, interfaces and automation.",
    },
    journey: {
      section_key: "journey",
      label: "Journey",
      title: "Experience",
      accent: "",
      description: "A concise view of practical work and ongoing technical exploration.",
    },
    contact: {
      section_key: "contact",
      label: "Contact",
      title: "Start a",
      accent: "Conversation",
      description: "Reach out for a project, collaboration or technical discussion.",
    },
  },
  socialLinks: [
    { id: 1, platform: "email", label: "Email", url: "mailto:sarthakbhandari172@gmail.com", icon_text: "EM", sort_order: 1, is_active: true, show_in_hero: false, show_in_contact: true, show_in_footer: true },
    { id: 2, platform: "github", label: "GitHub", url: "https://github.com/sarthakbhandari172-blip", icon_text: "GH", sort_order: 2, is_active: true, show_in_hero: true, show_in_contact: true, show_in_footer: true },
    { id: 3, platform: "linkedin", label: "LinkedIn", url: "https://www.linkedin.com/in/sarthak-bhandari-1303b0365/", icon_text: "LI", sort_order: 3, is_active: true, show_in_hero: false, show_in_contact: true, show_in_footer: true },
    { id: 4, platform: "instagram", label: "Instagram", url: "https://www.instagram.com/_hell.spawn", icon_text: "IG", sort_order: 4, is_active: true, show_in_hero: false, show_in_contact: true, show_in_footer: true },
    { id: 5, platform: "whatsapp", label: "WhatsApp", url: "https://wa.me/9779769291674", icon_text: "WA", sort_order: 5, is_active: true, show_in_hero: false, show_in_contact: true, show_in_footer: true },
  ],
  settings: {
    about_approach: "Explore → prototype → refine",
    about_mode: "Learning through practical projects",
    about_tools: "Design, web, automation and physical computing",
    hero_class: "Digital creative",
    hero_region: "Kathmandu, Nepal",
    hero_system_state: "Portfolio system online",
    footer_signature: "Built across design, code and curiosity",
  },
};
