import type { PortfolioData } from "@/lib/types";

const project = (p: {
  id: number; title: string; slug: string; category: string; description: string;
  tech_stack: string[]; thumbnail_url: string; sort_order: number; icon_text: string;
  github_url?: string | null; live_url?: string | null;
}) => ({
  external_url: null,
  live_url: p.live_url ?? "#",
  github_url: p.github_url ?? null,
  featured: true,
  is_active: true,
  thumbnail_fit: "cover" as const,
  thumbnail_position: "center center",
  ...p,
});

export const fallbackData: PortfolioData = {
  profile: {
    full_name: "Sarthak Bhandari",
    tagline: "Design · Content · Code",
    bio: "Graphic and digital designer with a developer's toolkit — creating brand, social and campaign visuals, then building them for the web.",
    avatar_url: "/media/profile/sb-mark.png",
    email: "sarthakbhandari172@gmail.com",
    location: "Kathmandu, Nepal",
    hero_label: "Sarthak Bhandari — Portfolio",
    hero_display_title: "Sarthak Bhandari",
    hero_accent_title: "Graphic & Digital Designer",
    hero_roles: ["Graphic & Digital Design", "Brand & Social Assets", "Design to Code, End to End"],
    hero_primary_cta_text: "View Work",
    hero_primary_cta_url: "#work",
    hero_secondary_cta_text: "What I Do",
    hero_secondary_cta_url: "#services",
    status_text: "Open to junior roles & freelance",
  },
  skills: [
    { id: 1, name: "Adobe Photoshop", category: "Design", proficiency: 75, icon: "PS", sort_order: 1 },
    { id: 2, name: "Adobe Illustrator", category: "Design", proficiency: 70, icon: "AI", sort_order: 2 },
    { id: 3, name: "Adobe Lightroom", category: "Design", proficiency: 70, icon: "LR", sort_order: 3 },
    { id: 4, name: "Figma", category: "Design", proficiency: 70, icon: "FG", sort_order: 4 },
    { id: 5, name: "Canva", category: "Design", proficiency: 90, icon: "CN", sort_order: 5 },
    { id: 6, name: "Premiere Pro & After Effects", category: "Motion", proficiency: 60, icon: "MO", sort_order: 6 },
    { id: 7, name: "CSS & Interface Design", category: "Code", proficiency: 90, icon: "UI", sort_order: 7 },
    { id: 8, name: "JavaScript / TypeScript", category: "Code", proficiency: 85, icon: "JS", sort_order: 8 },
    { id: 9, name: "Next.js & Supabase", category: "Code", proficiency: 70, icon: "NX", sort_order: 9 },
    { id: 10, name: "Git & GitHub", category: "Code", proficiency: 80, icon: "GT", sort_order: 10 },
  ],
  projects: [
    project({
      id: 3, sort_order: 1, icon_text: "BR",
      title: "LEKH Trail Gear", slug: "lekh-trail-gear", category: "Brand Identity — Concept",
      description: "Self-initiated brand for a fictional Kathmandu trekking gear label: logomark, palette, type system, social set and merch print.",
      tech_stack: ["Illustrator", "Figma", "Photoshop"],
      thumbnail_url: "/media/projects/lekh-brand.png",
    }),
    project({
      id: 12, sort_order: 2, icon_text: "LP",
      title: "Loopwise", slug: "loopwise", category: "Web Design — Concept",
      description: "SaaS landing page for a fictional team-time product: honest hero copy, product shot, proof strip and one CTA repeated.",
      tech_stack: ["Figma", "HTML & CSS"],
      thumbnail_url: "/media/projects/loopwise-saas.png",
    }),
    project({
      id: 13, sort_order: 3, icon_text: "EC",
      title: "Arc & Oak", slug: "arc-and-oak", category: "E-commerce UI — Concept",
      description: "Product page for a fictional furniture store: serif brand voice, full purchase-flow anatomy, finish swatches and reviews.",
      tech_stack: ["Figma"],
      thumbnail_url: "/media/projects/arcoak-ecom.png",
    }),
    project({
      id: 14, sort_order: 6, icon_text: "AD",
      title: "Stride — Ad Set", slug: "stride-ads", category: "Ad Creative — Concept",
      description: "Paid-social set for a fictional running app: one message adapted across feed, story and display placements.",
      tech_stack: ["Photoshop", "Figma"],
      thumbnail_url: "/media/projects/stride-ads.png",
    }),
    project({
      id: 4, sort_order: 4, icon_text: "CP",
      title: "Saath — साथ", slug: "saath-campaign", category: "Awareness Campaign — Concept",
      description: "Dementia-awareness concept campaign: two poster directions and a social adaptation, designed to accessible contrast standards.",
      tech_stack: ["Figma", "Photoshop"],
      thumbnail_url: "/media/projects/saath-campaign.png",
    }),
    project({
      id: 5, sort_order: 3, icon_text: "YT",
      title: "Trail Nepal — Thumbnail System", slug: "trail-nepal-thumbnails", category: "Content Design — Concept",
      description: "Click-through YouTube thumbnail system for a fictional trekking channel — one type stack, one accent, readable at 168 px.",
      tech_stack: ["Photoshop", "Figma"],
      thumbnail_url: "/media/projects/yt-thumbs.png",
    }),
    project({
      id: 6, sort_order: 4, icon_text: "DB",
      title: "Nepse Pulse", slug: "nepse-pulse", category: "Dashboard UI — Concept",
      description: "Dark fintech dashboard for Nepal's stock market: index overview, watchlist and one-week chart — sample data throughout.",
      tech_stack: ["Figma"],
      thumbnail_url: "/media/projects/nepse-dash.png",
    }),
    project({
      id: 7, sort_order: 5, icon_text: "UI",
      title: "Lekh App", slug: "lekh-app", category: "Mobile UI — Concept",
      description: "Trail-companion app for the LEKH brand: wireframes to hi-fi screens — home, trail detail, packing checklist.",
      tech_stack: ["Figma"],
      thumbnail_url: "/media/projects/lekh-app.png",
    }),
    project({
      id: 8, sort_order: 6, icon_text: "ED",
      title: "PAILA Quarterly", slug: "paila-editorial", category: "Editorial — Concept",
      description: "Cover and feature spread for a fictional Kathmandu design magazine: hand-painted street signboards vs the vinyl-print flood.",
      tech_stack: ["Figma", "InDesign"],
      thumbnail_url: "/media/projects/paila-editorial.png",
    }),
    project({
      id: 9, sort_order: 7, icon_text: "LG",
      title: "Logofolio Vol. 01", slug: "logofolio-01", category: "Brand Marks — Concept",
      description: "Six marks for six fictional clients — one line weight, positive and reversed, built to survive at favicon size.",
      tech_stack: ["Illustrator"],
      thumbnail_url: "/media/projects/logofolio.png",
    }),
    project({
      id: 10, sort_order: 8, icon_text: "PK",
      title: "Himali Chiya", slug: "himali-chiya", category: "Packaging — Concept",
      description: "Tea packaging for a fictional Ilam estate: teal and gold pouch, bilingual label system, three-flavour line extension.",
      tech_stack: ["Illustrator", "Photoshop"],
      thumbnail_url: "/media/projects/chiya-packaging.png",
    }),
    project({
      id: 11, sort_order: 9, icon_text: "PO",
      title: "Patan Sessions Vol. 03", slug: "patan-sessions", category: "Poster — Concept",
      description: "Two-colour risograph gig poster for a fictional courtyard concert series — deliberate misregistration, bilingual type.",
      tech_stack: ["Illustrator"],
      thumbnail_url: "/media/projects/gig-poster.png",
    }),
    project({
      id: 1, sort_order: 10, icon_text: "WEB",
      title: "Portfolio Engine", slug: "portfolio-engine", category: "Design + Build",
      description: "Designed and built end to end — visual system, responsive interface and an authenticated content dashboard.",
      tech_stack: ["Figma", "Next.js", "Supabase", "TypeScript"],
      thumbnail_url: "/media/projects/portfolio-engine.png",
      github_url: "https://github.com/sarthakbhandari172-blip",
    }),
    project({
      id: 2, sort_order: 11, icon_text: "UI",
      title: "Interface Experiments", slug: "interface-experiments", category: "UI Systems",
      description: "Interface studies focused on motion, hierarchy and clear technical presentation.",
      tech_stack: ["CSS", "JavaScript", "Figma"],
      thumbnail_url: "/media/projects/interface-experiments.png",
      github_url: "https://github.com/sarthakbhandari172-blip",
    }),
  ],
  experience: [
    {
      id: 1,
      company: "Freelance & self-initiated briefs",
      role: "Independent Visual Designer",
      period: "2025 — Present",
      description: "Brand identity concepts, social media and campaign-style assets, presentation decks, photo retouching and print-ready artwork — delivered organised and on time.",
      icon: "01",
      status: "Current",
      sort_order: 1,
    },
    {
      id: 2,
      company: "Independent Projects",
      role: "Software & Interface Development",
      period: "2025 — Present",
      description: "Building web interfaces and database-backed applications, end to end.",
      icon: "02",
      status: "Current",
      sort_order: 2,
    },
    {
      id: 4,
      company: "Canva Design School",
      role: "Certified — Graphic Design Essentials",
      period: "Sept 2026",
      description: "Canva certification in graphic design foundations. Credential ID 505afa — click to verify.",
      icon: "04",
      status: "Certified",
      sort_order: 4,
    },
    {
      id: 3,
      company: "Hardware Exploration",
      role: "Prototyping & Systems Learning",
      period: "2024 — Present",
      description: "Electronics and physical computing — the connection between hardware and software.",
      icon: "03",
      status: "Ongoing",
      sort_order: 3,
    },
  ],
  services: [
    ["Brand & Social Graphics", "Logo concepts, identity elements and social assets that stay consistent across every format.", "BR"],
    ["Campaign & Poster Design", "Posters, banners and campaign visuals for events, causes and products — digital or print-ready.", "CP"],
    ["Photo Editing & Retouching", "Colour, composition and clean-up in Photoshop and Lightroom.", "RT"],
    ["Presentation Design", "Clear, on-brand decks that make information easy to follow.", "PD"],
    ["Landing Pages", "Single-purpose pages designed around one message and one clear action.", "LP"],
    ["Business & Portfolio Websites", "Responsive sites structured around clear content and usability — designed and built.", "WB"],
    ["Website Redesign", "Interface and structure improvements for existing websites.", "UI"],
    ["AI-Assisted Workflows", "Ideation with Midjourney, Firefly and Canva AI — always selected, composited and finished by hand.", "AW"],
  ].map(([title, description, icon_text], index) => ({
    id: index + 1,
    title,
    description,
    icon_text,
    badge_text: "Service",
    badge_style: index % 2 ? "cyan" : "ok",
    cta_text: "Discuss project",
    cta_url: "#contact",
    sort_order: index + 1,
    is_active: true,
  })),
  sections: {
    about: {
      section_key: "about",
      label: "About",
      title: "About",
      accent: "Sarthak",
      description: "Graphic and digital designer from Kathmandu who combines visual craft with the ability to build for the web.",
    },
    skills: {
      section_key: "skills",
      label: "Toolkit",
      title: "Tools &",
      accent: "Skills",
      description: "Design tools first, backed by real front-end development.",
    },
    work: {
      section_key: "work",
      label: "Selected Work",
      title: "Featured",
      accent: "Projects",
      description: "Eleven projects across brand, campaign, editorial, packaging, content and UI — concept briefs clearly labelled.",
    },
    services: {
      section_key: "services",
      label: "What I Do",
      title: "What I",
      accent: "Do",
      description: "Design and digital services for brands, causes and small teams.",
    },
    journey: {
      section_key: "journey",
      label: "Journey",
      title: "Experience",
      accent: "",
      description: "Freelance design work, independent builds and ongoing learning.",
    },
    contact: {
      section_key: "contact",
      label: "Contact",
      title: "Start a",
      accent: "Conversation",
      description: "Reach out about a role, a project or a collaboration.",
    },
  },
  socialLinks: [
    { id: 1, platform: "email", label: "Email", url: "mailto:sarthakbhandari172@gmail.com", icon_text: "EM", sort_order: 1, is_active: true, show_in_hero: false, show_in_contact: true, show_in_footer: true },
    { id: 2, platform: "github", label: "GitHub", url: "https://github.com/sarthakbhandari172-blip", icon_text: "GH", sort_order: 2, is_active: true, show_in_hero: true, show_in_contact: true, show_in_footer: true },
    { id: 3, platform: "linkedin", label: "LinkedIn", url: "https://www.linkedin.com/in/sarthak-bhandari-1303b0365/", icon_text: "LI", sort_order: 3, is_active: true, show_in_hero: false, show_in_contact: true, show_in_footer: true },
    { id: 4, platform: "instagram", label: "Instagram", url: "https://www.instagram.com/_hell.spawn", icon_text: "IG", sort_order: 4, is_active: true, show_in_hero: false, show_in_contact: true, show_in_footer: true },
    { id: 5, platform: "whatsapp", label: "WhatsApp", url: "https://wa.me/9779769291674", icon_text: "WA", sort_order: 5, is_active: true, show_in_hero: false, show_in_contact: true, show_in_footer: true },
  ],
  settings: {
    about_approach: "Explore → prototype → refine",
    about_mode: "Learning by shipping real projects",
    about_tools: "Figma, Adobe Creative Cloud and the modern web",
    hero_class: "Graphic & digital designer",
    hero_region: "Kathmandu, Nepal",
    hero_system_state: "Open to junior roles & freelance",
    footer_signature: "Built across design, code and curiosity",
  },
};
