create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.profile (
  id bigint generated by default as identity primary key,
  full_name text not null,
  tagline text,
  bio text,
  avatar_url text,
  email text,
  phone text,
  location text,
  resume_url text,
  updated_at timestamptz not null default now()
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  proficiency integer not null default 50 check (proficiency between 0 and 100),
  icon text,
  sort_order integer not null default 0
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  category text,
  description text,
  tech_stack text[] not null default '{}',
  thumbnail_url text,
  external_url text,
  live_url text,
  github_url text,
  icon_text text,
  featured boolean not null default false,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  thumbnail_fit text not null default 'cover' check (thumbnail_fit in ('cover', 'contain')),
  thumbnail_position text not null default 'center center',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.experience (
  id bigint generated by default as identity primary key,
  company text not null,
  role text not null,
  start_date date,
  end_date date,
  period text,
  description text,
  icon text,
  status text,
  sort_order integer not null default 0
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  icon_text text,
  badge_text text,
  badge_style text,
  cta_text text,
  cta_url text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.section_content (
  section_key text primary key,
  label text,
  title text,
  accent text,
  description text,
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  sender_name text not null check (char_length(sender_name) between 2 and 120),
  sender_email text not null check (char_length(sender_email) between 5 and 254),
  subject text,
  message text not null check (char_length(message) between 10 and 5000),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  setting_key text primary key,
  setting_value text
);

create table if not exists public.social_links (
  id bigint generated by default as identity primary key,
  platform text not null,
  label text not null,
  url text not null,
  icon_text text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  show_in_hero boolean not null default true,
  show_in_contact boolean not null default true,
  show_in_footer boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

drop trigger if exists profile_set_updated_at on public.profile;
create trigger profile_set_updated_at before update on public.profile
for each row execute function public.set_updated_at();

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at before update on public.projects
for each row execute function public.set_updated_at();

drop trigger if exists services_set_updated_at on public.services;
create trigger services_set_updated_at before update on public.services
for each row execute function public.set_updated_at();

drop trigger if exists section_content_set_updated_at on public.section_content;
create trigger section_content_set_updated_at before update on public.section_content
for each row execute function public.set_updated_at();

drop trigger if exists social_links_set_updated_at on public.social_links;
create trigger social_links_set_updated_at before update on public.social_links
for each row execute function public.set_updated_at();

alter table public.admin_users enable row level security;
alter table public.profile enable row level security;
alter table public.skills enable row level security;
alter table public.projects enable row level security;
alter table public.experience enable row level security;
alter table public.services enable row level security;
alter table public.section_content enable row level security;
alter table public.contact_messages enable row level security;
alter table public.settings enable row level security;
alter table public.social_links enable row level security;

create policy "Admins can view their admin record"
on public.admin_users for select to authenticated
using (user_id = auth.uid());

create policy "Public can read profile"
on public.profile for select to anon, authenticated using (true);
create policy "Public can read skills"
on public.skills for select to anon, authenticated using (true);
create policy "Public can read active projects"
on public.projects for select to anon, authenticated using (is_active or public.is_admin());
create policy "Public can read experience"
on public.experience for select to anon, authenticated using (true);
create policy "Public can read active services"
on public.services for select to anon, authenticated using (is_active or public.is_admin());
create policy "Public can read section copy"
on public.section_content for select to anon, authenticated using (true);
create policy "Public can read settings"
on public.settings for select to anon, authenticated using (true);
create policy "Public can read active social links"
on public.social_links for select to anon, authenticated using (is_active or public.is_admin());

create policy "Admins manage profile"
on public.profile for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage skills"
on public.skills for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage projects"
on public.projects for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage experience"
on public.experience for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage services"
on public.services for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage section copy"
on public.section_content for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "Admins read contact messages"
on public.contact_messages for select to authenticated
using (public.is_admin());
create policy "Admins update contact messages"
on public.contact_messages for update to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "Admins delete contact messages"
on public.contact_messages for delete to authenticated
using (public.is_admin());
create policy "Admins manage settings"
on public.settings for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage social links"
on public.social_links for all to authenticated
using (public.is_admin()) with check (public.is_admin());

insert into storage.buckets (id, name, public)
values ('portfolio-media', 'portfolio-media', true)
on conflict (id) do update set public = excluded.public;

create policy "Admins upload portfolio media"
on storage.objects for insert to authenticated
with check (bucket_id = 'portfolio-media' and public.is_admin());
create policy "Admins update portfolio media"
on storage.objects for update to authenticated
using (bucket_id = 'portfolio-media' and public.is_admin())
with check (bucket_id = 'portfolio-media' and public.is_admin());
create policy "Admins delete portfolio media"
on storage.objects for delete to authenticated
using (bucket_id = 'portfolio-media' and public.is_admin());

grant usage on schema public to anon, authenticated;
grant select on public.profile, public.skills, public.projects, public.experience,
  public.services, public.section_content, public.settings, public.social_links
to anon, authenticated;
grant all on public.profile, public.skills, public.projects, public.experience,
  public.services, public.section_content, public.contact_messages,
  public.settings, public.social_links
to authenticated;
grant usage, select on all sequences in schema public to authenticated;

